name: mool
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  flutter_svg: ^2.0.17
  # country_picker: ^2.0.27
  country_picker: ^2.0.27
  intl_phone_field: ^3.2.0
  flutter_social_button: ^1.1.6+1
  transparent_image: ^2.0.1
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1

flutter_icons:
  android: true
  image_path: "images/mool_app_icon.png"

  # csc_picker: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/mool_back.png
    - images/mool_logo.png
    - images/welcome.png
    - images/arrow-square-left.png
    - images/arrow-square-left.svg
    - images/sign_image.jpg
    - images/signup_background.png
    - images/register_back.png
    - images/signin_back.png
    - images/google.png
    - images/apple.png
    - images/facebook.png
    - images/otp.png
    - images/otp.svg
    - images/tops.png
    - images/bottoms.png
    - images/dresses.png
    - images/search-normal.svg
    - images/flash_sale.png
    - images/view_all.png
    - images/tshirts.png
    - images/sale.png
    - images/nightwear.png
    - images/notification.svg
    - images/truck-fast.svg
    - images/collection_1.png
    - images/collection_2.png
    - images/accessories.png
    - images/vacation_wear.png
    - images/h_m.png
    - images/loft.png
    - images/zara.png
    - images/nike.png
    - images/chanel.png
    - images/levi_s.png
    - images/red_dress.png
    - images/yellow_dress.png
    - images/pink_dress.png
    - images/gray_top.png
    - images/night_wear.png
    - images/notify.png
    - images/elegant_blazer.png
    - images/user.svg
    - images/myaccount/global.svg
    - images/myaccount/heart.svg
    - images/myaccount/information.svg
    - images/myaccount/language-square.svg
    - images/myaccount/location.svg
    - images/myaccount/lock.svg
    - images/myaccount/logout.svg
    - images/myaccount/message-text.svg
    - images/myaccount/user-square.svg
    - images/myaccount/box.svg
    - images/master_card.svg
    - images/visa.svg
    - images/pay_mob.svg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: fonts/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Roboto-ExtraLight.ttf
          weight: 200
        - asset: fonts/Roboto-ExtraLightItalic.ttf
          weight: 200
          style: italic
